config/routes.rb
MassTriage::Application.routes.draw do
 
  
  
  resources :incident_types

  match "login", :to => "user_sessions#new", :as => :login
  
  match "logout", :to => "user_sessions#destroy", :as => :logout

  match "patients/other", :to => "patients#other"
  
  match "administrators/index"  => "administrators#index", :as => "administrators"
  
  match "join_incident", :to => "incidents#join_incident", :as => :join_incident

  resources :user_sessions

  resources :users

  resources :hospitals

  

  resources :responders

  match "incidents/:id/closeincident" => "incidents#closeincident", :as => "closeincident"
  match "incidents/:incident_id/viewupdate" => "incidents#viewupdate", :as => "viewupdate"
  match "incidents/:incident_id/resourceupdate" => "incidents#resourceupdate", :as => "resourceupdate"
  match "incidents/:incident_id/patient_count" => "incidents#patient_count", :as => "patient_count"
  match "incidents/report" => "incidents#report", :as => "report"
  match "viewreport/:id" => "incidents#viewreport", :as => "viewreport"
  
  resources :incidents do
    resources :ambulances
    resources :patients
    member do
      get 'close'
    end
    
  end

 
  
  root :to => 'incidents#index'

end

app/models/ambulance.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class Ambulance < ActiveRecord::Base
  belongs_to :incident
  has_many :patients
  belongs_to :hospital  
end

app/controllers/ambulances_controller.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class AmbulancesController < ApplicationController
 layout 'patient'
 before_filter :require_user

 def index
   @incident = Incident.find(params[:incident_id])
   @patients = @incident.patients.all
   @ambulance = @incident.ambulances.new
   @ambulances = @incident.ambulances.all
    
   @hospitals = Hospital.find :all, :conditions => ['is_deleted is not ? ', true]   
   @incidentType = IncidentType.find :all, :conditions => ['is_deleted is not ? ', true]
   @stringIncidentType = json_incidentType(@incidentType)   

   @oddOrEven = 0
   respond_to do |format|
     format.html
     format.xml  { render :xml => @ambulances }
   end
 end

 def show
   @ambulance = Ambulance.find(params[:id])

   respond_to do |format|
     format.html
     format.xml  { render :xml => @ambulance }
   end
 end

 def new
   @incident = Incident.find(params[:incident_id])
   @ambulance = @incident.ambulances.new
   @patients = @incident.patients.all

   respond_to do |format|
     format.html
     format.xml  { render :xml => @ambulance }
   end
 end

 def edit
   @incident = Incident.find(params[:incident_id])
   @ambulance = @incident.ambulances.find(params[:id])
   @patients = @incident.patients.all
 end

 def create
   @incident = Incident.find(params[:incident_id])
   @ambulance = @incident.ambulances.new(params[:ambulance])
   @ambulance.adding_user_id = current_user.id
   @ambulance.is_deleted = false;

   if(@ambulance.eta < Time.now())
     @ambulance.eta = @ambulance.eta + 1.day
   end
    
   respond_to do |format|
     if @ambulance.save
       format.html { redirect_to(incident_ambulances_path, :notice => 'Ambulance was successfully created.') }
       format.xml  { render :xml => @ambulance, :status => :created, :location => @ambulance }
     else
       format.html { render :action => "new" }
       format.xml  { render :xml => @ambulance.errors, :status => :unprocessable_entity }
     end
   end
 end

 def update
   @incident = Incident.find(params[:incident_id])
   @ambulance = @incident.ambulances.find(params[:id])
    
   respond_to do |format|
     if(params[:ambulance])
       if(@ambulance.eta < Time.now())
         @ambulance.eta = @ambulance.eta + 1.day
       end
 
       if @ambulance.update_attributes(params[:ambulance])
         flash[:notice] = "Ambulance successfully updated."
         if params[:ambulance][:idAmbulance]
           format.html {  render :text => params[:ambulance][:idAmbulance] }
           format.json  { head :ok }
         elsif params[:ambulance][:status]
           format.html {  render :text => params[:ambulance][:status] }
           format.json  { head :ok }
         elsif params[:ambulance][:hospital]
           format.html {  render :text => params[:ambulance][:hospital] }
           format.json  { head :ok }
         elsif params[:ambulance][:eta]
           format.html {  render :text => params[:ambulance][:eta] }
           format.json  { head :ok }
         end
       end
     else  
       if @ambulance.update_attributes(:hospital_id => params[:hospital][:name])
         @new_hospital = Hospital.find(params[:hospital][:name])
         format.html {  render :text => @new_hospital.name }
         format.json  { head :ok }
       end
     end
   end
 end

 def destroy    
   @incident = Incident.find(params[:incident_id])
   @ambulance = @incident.ambulances.find(params[:id])
   if(@ambulance.idAmbulance != "Not yet defined")
     if(@ambulance.update_attributes(:is_deleted => true ))
       respond_to do |format|
         format.html { redirect_to (incident_ambulances_url) }
         format.js
       end
     end
   end
 end
 
 def json_incidentType(incidentType)
   hashIncidentType = Hash.new
   incidentType.each do |incidentType|
     hashIncidentType[incidentType.id] = incidentType.name
   end
   
   return JSON.generate(hashIncidentType)
 end
    
end

app/helpers/ambulances_helper.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

module AmbulancesHelper
end

app/views/ambulances/_ambulance.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->
<% if @incident.status == true %>
	<% if ambulance.idAmbulance != "Not yet defined"%>
		<% if ambulance.is_deleted != true %>
			<% if @oddOrEven % 2 == 0 %>
				<tr id="ambulance_<%= ambulance.id %>" class = "even">
			<%else %>
				<tr id="ambulance_<%= ambulance.id %>" >
			<% end %>
			
			<% @oddOrEven+=1%>
	
			<td>
				<%= editable_field ambulance, :idAmbulance, {:update_url => incident_ambulance_path(@incident, ambulance)} %>
			</td>
			<td>
				<%= editable_field ambulance, :status, :type => 'select', :onblur => 'submit', :update_url => incident_ambulance_path(@incident, ambulance), :data => {'En Route', 'En Route', 'Delayed', 'Delayed', 'Staging', 'Staging', 'At Scene', 'At Scene', 'Transported', 'Transported'}%>
			</td>

			<td >
				<% hospital = Hospital.find(ambulance.hospital_id) %>
				<span class="editable" data-id="<%=ambulance.id%>" data-name="hospital[name]">
					<%= hospital.name %>
				</span>
				<script type="text/javascript">
					function listHospitals(){
						var hospitalList = '{';
						<% for a in @hospitals %>
							hospitalList = hospitalList + '"<%= a.id %>":"<%= escape_javascript(a.name) %>",';
						<% end %>
						hospitalList = hospitalList.substring(0, hospitalList.length-1);
						return hospitalList + '}';
					}
					(function( $ ){
						$(function(){
							var args = {data: function(value, settings) {
								// Unescape HTML
								var retval = value
								.replace(/&amp;/gi, '&')
								.replace(/&gt;/gi, '>')
								.replace(/&lt;/gi, '<')
								.replace(/&quot;/gi, "\"");
								return retval;
							}};
							$.extend(args, {"name":"hospital[name]","data":listHospitals(),"onblur":"submit","method":"PUT","type":"select"});
							$(".editable[data-id='<%=  ambulance.id %>'][data-name='hospital[name]']").editable("<%= incident_ambulance_path(@incident, ambulance.id) %>", args);
						});
					})( jQuery );
				</script>
			</td>
		
			<td>
				<%= editable_field ambulance, :eta, {:update_url => incident_ambulance_path(@incident, ambulance)} %>
			</td>
			<td>
				<%= button_to "X", [@incident, ambulance], :method=>:delete, :class=>:destroy, :confirm=>"Are you sure?", :remote => true %>
			</td>
		</tr>
		<% end %>
	<% end %>
<% else %>

<% if ambulance.idAmbulance != "Not yet defined"%>
	<% if ambulance.is_deleted != true %>
		<% if @oddOrEven % 2 == 0 %>
      		<tr id="ambulance_<%= ambulance.id %>" class = "even">
	  	<%else %>
	  		<tr id="ambulance_<%= ambulance.id %>" >
	  	<% end %>
	  	<% @oddOrEven+=1%>	
        <td>
			<%= ambulance.idAmbulance%>
		</td>
        <td>
			<%= ambulance.status%>
		</td>

		<td >
			<% hospital = Hospital.find(ambulance.hospital_id) %>
			<span class="editable" data-id="<%=ambulance.id%>" data-name="hospital[name]">
				<%= hospital.name %>
			</span>
		</td>
		
        <td>
			<%= ambulance.eta %>
		</td>
        
		</tr>
		<% end %>
	<% end %>
<% end %>

app/views/ambulances/_form.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<%= form_for [@incident, @ambulance] do |ambulance| %>
	<%= ambulance.label :idAmbulance, "Ambulance Number" %>
	<%= ambulance.text_field :idAmbulance %>
	<%= ambulance.select :status, [['En Route','En Route'],['Delayed','Delayed'],['At Scene','At Scene'],['Transported','Transported'],['Staging','Staging']] %>
	<%= ambulance.label :eta, "ETA"%>
	<%= ambulance.time_select :eta %>
	<%= ambulance.submit "ADD"%>
<% end %> 

app/views/ambulances/destroy.js.erb
/*
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
*/

/* Eliminate the patient by fading it out */
$('#ambulance_<%= @ambulance.id %>').fadeOut();

/* Replace the count of patient */
$("#ambulance_count").html("<%= pluralize(Ambulance.count, 'Ambulance') %>");

$('.delete_ambulance').bind('ajax:success', function() {  
    $(this).closest('tr').fadeOut();  
});

app/views/ambulances/edit.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h1>Editing ambulance</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_ambulances_path %>

app/views/ambulances/index.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h2>
	<span class ="UnselectedTab">
		<%= link_to "TRIAGE", incident_patients_path(@incident) %>
	</span>   
	<span class ="SelectedTab">
		AMBULANCE
	</span>     
	<span class ="UnselectedTab">
		<%= link_to "CLOSE", close_incident_path(@incident) %>
	</span>
</h2>

<hr />

<div id="incident" data-id="<%= @incident.id %>"></div>
<div id="incident_info" data-id="<%= @incident.id %>"></div>

<%if @incident.status == true%>
	<% if current_user %>
  		<% if User.find(current_user.id).role_id == 2 %>
  			<%= render 'form' %>
  		<% elsif User.find(current_user.id).role_id == 1 %>
    	<% form_for @incident, :url=> viewupdate_path do |f|%>
			<% if @incident.errors.any? %>
    			<div id="error_explanation">
      				<h2>
						<%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:
					</h2>
					<ul>
      					<% @incident.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      					<% end %>
      				</ul>
    			</div>
  			<% end %>

			<div class="CountInputs">
				<h1>REQUEST AMBULANCES</h1>
				<br />
				<%= submit_tag "-5", :type=> 'button', :class => 'minus5Ambulance'%>
				<%= submit_tag "-1", :type=> 'button', :class => 'minus1Ambulance'%>
				<%= f.text_field :requested_amb_count, :value => '0', :id => 'fieldAmbulance'  %>
				<%= submit_tag "+1", :type=> 'button', :class => 'plus1Ambulance'%>
				<%= submit_tag "+5", :type=> 'button', :class => 'plus5Ambulance'%>
				<br /><br />
				<%= f.submit "NOTIFY DISPATCH", :class => 'LongButton'%>
				<br /><br/>
			</div>
			<% end -%>
		<% end -%>
	<% end -%>
<% else -%>
	<h1>THIS INCIDENT HAS BEEN CLOSED</h1>
<%end -%>

<hr />
<div class="centerEverythingContainterNoBorder">
	<div class="scrollable3">
		<table id="mciTable" class="tablesorter">
			<tr>
    			<th>AMBULANCE</th>
    			<th>STATUS</th>
    			<th>HOSPITAL</th>
    			<th>ETA</th>
				<th>REMOVE
			</tr>		
		<%= render :partial => @ambulances, :locals => {:list => true} %>
		</table>
	</div>
</div>

app/views/ambulances/new.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h1>New ambulance</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_ambulances_path %>

app/views/ambulances/show.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<p id="notice"><%= notice %></p>

<p>
  <b>Idambulance:</b>
  <%= @ambulance.idAmbulance %>
</p>

<p>
  <b>Description:</b>
  <%= @ambulance.description %>
</p>

<p>
  <b>Description:</b>
  <%= @ambulance.description %>
</p>

<p>
  <b>Description:</b>
  <%= @ambulance.description %>
</p>

<p>
  <b>Description:</b>
  <%= @ambulance.description %>
</p>

<%= link_to 'Edit', edit_ambulance_path(@ambulance) %> |
<%= link_to 'Back', ambulances_path %>