config/routes.rb
MassTriage::Application.routes.draw do
 
  
  
  resources :incident_types

  match "login", :to => "user_sessions#new", :as => :login
  
  match "logout", :to => "user_sessions#destroy", :as => :logout

  match "patients/other", :to => "patients#other"
  
  match "administrators/index"  => "administrators#index", :as => "administrators"
  
  match "join_incident", :to => "incidents#join_incident", :as => :join_incident

  resources :user_sessions

  resources :users

  resources :hospitals

  

  resources :responders

  match "incidents/:id/closeincident" => "incidents#closeincident", :as => "closeincident"
  match "incidents/:incident_id/viewupdate" => "incidents#viewupdate", :as => "viewupdate"
  match "incidents/:incident_id/resourceupdate" => "incidents#resourceupdate", :as => "resourceupdate"
  match "incidents/:incident_id/patient_count" => "incidents#patient_count", :as => "patient_count"
  match "incidents/report" => "incidents#report", :as => "report"
  match "viewreport/:id" => "incidents#viewreport", :as => "viewreport"
  
  resources :incidents do
    resources :ambulances
    resources :patients
    member do
      get 'close'
    end
    
  end

 
  
  root :to => 'incidents#index'

end

app/models/incident.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class Incident < ActiveRecord::Base 
  
  has_many :ambulances
  has_many :patients
  has_and_belongs_to_many :users
  
  validates_numericality_of :est_patient_count, :only_integer => true, :allow_nil => true, :greater_than => -1, :on => :update
  validates_numericality_of :requested_amb_count, :only_integer => true, :allow_nil => true, :greater_than => -1, :on => :update
  validates_numericality_of :latitude, :only_integer => false, :allow_nil => true
  validates_numericality_of :longitude, :only_integer => false, :allow_nil => true
  validates_presence_of :date, :on => :create, :message => "can't be blank"

  def color_dist(color, id)
   patients_untrasported = Patient.find :all, :conditions => ['tagColor = ? AND is_deleted = ? AND incident_id = ?', color, false, id]
   patients_untrasported.count
  end
  
  def amb_count(status, id)
    ambulances_count = Ambulance.find :all, :conditions => ['status = ? AND is_deleted is not ? AND incident_id = ?', status, true, id]
    return ambulances_count.count
  end
  
  def total_ambulances(id)
     total_ambulances = Ambulance.find :all, :conditions => ['is_deleted is not ? AND incident_id = ?', true, id]
     return total_ambulances.count
  end
  
  def untransported(status, id)
    patients_untrasported = Patient.find :all, :conditions => ['status = ? AND is_deleted = ? AND incident_id = ?', status, false, id]
    if patients_untrasported.count.to_s == 0
      return "There are no untransported patients listed at the incident"
    elsif patients_untrasported.count.to_s == 1
      return "There is currently 1 untransported patient listed at the incident"
    else
      return "There are currently " << patients_untrasported.count.to_s << " untransported patients listed at the incident"
    end
  end
  
  def count_patient(id)
    patients_tagged = Patient.find :all, :conditions => ['is_deleted = ? AND incident_id = ?', false, id]
    return patients_tagged
  end

end

app/models/incident_type.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class IncidentType < ActiveRecord::Base
  validates_uniqueness_of :name, :on => :create, :message => "must be unique"
end

app/controllers/incidents_controller.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class IncidentsController < ApplicationController
  before_filter :require_user
  helper :incidents
  
  def index
    if(@current_user.role_id == 3)
      @incidents = Incident.all
    else
      @incidents = Incident.find_all_by_status(true)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @incidents }
    end
  end

  def show
    @incident = Incident.find(params[:id])
       
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @incident }
    end
  end

  def new
    @incident = Incident.new
    @incident.date = Time.now()
    @incident_type = IncidentType.find :all, :conditions => ['is_deleted is not ?', true]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @incident }
    end
  end

  def edit
    @incident = Incident.find(params[:id])
  end


  def create  
    @incident = Incident.new(params[:incident])
    puts "Incident location " << @incident.location
    if(current_user != nil)
      @incident.creating_user_id = current_user.id
      @user = User.find(current_user.id)
      if @user.role_id != 3
        @incident.users.push(@user)
      end
    end
    if(params[:incident][:location] == "")
      @incident.location = 'No location specified'
    end
    if (params[:incident][:latitude] == "")
      @incident.latitude = 0
    end
    if(params[:incident][:longitude] == "")
       @incident.longitude = 0
    end
      
    respond_to do |format|
      if @incident.save
        hospital = Hospital.find(:first, :conditions => {:name => "Not yet defined"})
        puts "Hospital name " << hospital.name
        ambulance = Ambulance.create(:idAmbulance => "Not yet defined", :incident_id => @incident.id, :hospital_id => hospital.id, :is_deleted => false )
        puts "Ambulance name" << ambulance.id
        format.html { redirect_to(patient_count_path(@incident), :notice => 'Incident was successfully created.') }
        format.xml  { render :xml => @incident, :status => :created, :location => @incident }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @incident = Incident.find(params[:id])
    if ((params[:incident][:requested_amb_count].to_i) < 0)
      params[:incident][:requested_amb_count] = 0
    end
    if ((params[:incident][:est_patient_count].to_i) < 0)
      params[:incident][:est_patient_count] = 0
    end
    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        if (params[:commit] == "BEGIN TRIAGE")
          format.html {redirect_to(incident_patients_path(@incident), :notice => 'Incident was successfully updated.')}
          format.xml  { head :ok }
        else
          format.html {redirect_to(incident_ambulances_path(@incident), :notice => 'Incident was successfully updated.')}
          format.xml  { head :ok }
        end
      else
        if(params[:commit] == "BEGIN TRIAGE")
          format.html { render :action => "patient_count" }
          format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
        end
      end
    end
  end 
  

  def resourceupdate
    @incident = Incident.find(params[:incident_id])
    respond_to do |format|
      if(params[:incident])
        if @incident.update_attributes(params[:incident])
          if params[:incident][:location]
            format.html {  render :text => params[:incident][:location] }
            format.json  { head :ok }
          elsif params[:incident][:latitude]
            format.html {  render :text => params[:incident][:latitude] }
            format.json  { head :ok }
          elsif params[:incident][:longitude]
            format.html {  render :text => params[:incident][:longitude] }
            format.json  { head :ok }
          elsif params[:incident][:description]
            format.html {  render :text => params[:incident][:description] }
            format.json  { head :ok }
          end
        end
      elsif(params[:incident_type])
        if(@incident.update_attributes(:incident_type_id => params[:incident_type][:name]))
          incidentTypeName = IncidentType.find(params[:incident_type][:name])
          format.html {  render :text => incidentTypeName.name  }
        end
      end
    end
  end
  
  def viewupdate
    @incident = Incident.find(params[:incident_id])
    
    if ((@incident.requested_amb_count + params[:incident][:requested_amb_count].to_i) < 0)
      params[:incident][:requested_amb_count] = 0
    else
      params[:incident][:requested_amb_count] = @incident.requested_amb_count + params[:incident][:requested_amb_count].to_i
    end
    
    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html {redirect_to(incident_ambulances_path(@incident), :notice => 'Incident was successfully updated.')}  
        format.xml  { head :ok }
      else
        format.html { redirect_to incident_ambulances_path }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end
  

  def destroy
    @incident = Incident.find(params[:id])
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to(incidents_url) }
      format.xml  { head :ok }
    end
  end
  
  def patient_count
    @incident = Incident.find(params[:incident_id])
  end


  def add_arrival
    @incident = Incident.find(params[:id])
    @incident.arrivalTime = Time.now()
    @incident.save

    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html {redirect_to(incidents_path, :notice => 'Incident arrival was successfully updated.')}
        format.xml  { head :ok }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def close
    @incident = Incident.find(params[:id])
    @patients = @incident.patients.all
    @hospitals = Hospital.all
    @incidentType = IncidentType.all
    @stringIncidentType = json_incidentType(@incidentType)
    @ambulances = @incident.ambulances.all
  end
  
  def closeincident
    @incident = Incident.find(params[:id])
    @incident.status = false
    @incident.closing_user_id = current_user.id
  
    respond_to do |format|
      if @incident.save
        format.html {redirect_to(incidents_path, :notice => 'Incident was successfully closed.')}
        format.xml  { head :ok }
      else
        format.html { redirect_to close_incident_path }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def json_incidentType(incidentType)
    hashIncidentType = Hash.new
    incidentType.each do |incidentType|
      hashIncidentType[incidentType.id] = incidentType.name
    end
    return JSON.generate(hashIncidentType)
  end

  def join_incident
    @incident = Incident.find(params[:id])
    @user = User.find(current_user.id)
    @incident.users.push(@user)

    respond_to do |format|
      if @incident.save
        format.html {redirect_to(incident_patients_path(params[:id]), :notice => 'You have successfully joined incident.')}
        format.xml  { head :ok }
      else
        format.html { redirect_to incidents_path }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end

  def report
    @incident = Incident.select("*").where("status = ?", false)
  end

  def viewreport
    @incident = Incident.find_by_id_and_status(params[:id], "f")
    if !@incident.nil?
      @patient =@incident.patients.all
      @incident_user = @incident.users.all
    end
  end
  
end

app/helpers/incidents_helper.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

module IncidentsHelper
  def added(incident)
    if incident.users.exists?(current_user.id)
      return true
    else
      return false
    end
  end

  def user(responderid)
    return @user = User.find(responderid)
  end

  def role(incident, roleid)
    return incident.users.find(:first, :conditions => "role_id= #{roleid}")
  end

  def updates(incidentid, patientid)
    return PatientUpdate.new.getupdates(incidentid, patientid)
  end

  def transport(incidentid, patientid)
    return  PatientUpdate.new.transported(incidentid, patientid)
  end

  def incidentcommander()
  end
  
end

app/views/incidents/close.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<div class="TopBar">
	<img class ="image"src ="../../images/LogoWhite.png"/>
    <br />
    <h1 class="TopBarInterior">CLOSE INCIDENT<hr /></h1>
  	<br/>
</div>
<div class="CountLogin">
	<div class="CountInputs">
    	<% if @incident.status == true %>
			<% untransported = @incident.untransported("At Scene", @incident.id) %>
			<br/>
			<span class="title"><%= @incident.untransported("At Scene", @incident.id) %></span>
			<br /><br />
			<h2>
				<%= link_to "TRIAGE", incident_patients_path(@incident) %>   
				<%= link_to "AMBULANCE", incident_ambulances_path(@incident)%>
			</h2>
  			EXIT THE INCIDENT AND GO TO THE INCIDENT LIST
			<br />
  			<%= link_to "EXIT", incidents_path %>
			<br /><br />
  			CLOSE THE INCIDENT AND MARK IT AS COMPLETED
			<br />
			<%= link_to "CLOSE INCIDENT", closeincident_path, :confirm => "Are you sure?\nThis will mark the triage and transportation\nprocess as completed!" %>
		<% else %>
  			<br />
  			<h2>THIS INCIDENT HAS BEEN CLOSED</h2>
			<br/><br/>
			<h2>
				<%= link_to "TRIAGE", incident_patients_path(@incident) %>   
				<%= link_to "AMBULANCE", incident_ambulances_path(@incident)%>
			</h2>
  			EXIT THE INCIDENT AND GO TO THE INCIDENT LIST<br />
  			<%= link_to "EXIT", incidents_path %><br /><br />
		<% end %>
  		<br /><br/>
	</div>
  	<br/><br/>
</div>

app/views/incidents/edit.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h1>Editing incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |

app/views/incidents/index.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications
-->

<% if @current_user %>
	<% if @current_user.role_id != 3 %>
		<div class="wrapper">
	<%end%>	
<%end%>
  
	<div class="TopBar">
		<img class ="image"src ="../images/LogoWhite.png"/>
    	<br />
		<h1 class="TopBarInterior">MCIs in Progress<hr /></h1><br />
	</div>
	<br />
  
<table id="mciTable">
	<tr>
    	<th class="date">DATE</th>
    	<th class ="type">TYPE</th>
    	<th class="location">LOCATION</th>
    	<th class="latitude">LAT</th>
    	<th class="longitude">LONG</th>
		<% if @current_user %>
			<% if @current_user.role_id == 3 %>
				<th class="open">OPEN?</th>
			<%end%>
		<%end%>
    	<th class="open"> </th>
  	</tr>

	<% @incidents.each_with_index do |incident, i| %>
		<% if i%2 == 0 %>
			<tr id ="even">
        <%else %>
			<tr>
        <% end%>

		<% if incident.date != nil %>
			<td>
				<%= incident.date.strftime("%m/%d/%y %H:%M:%S %p %Z") %>
			</td>
    	<% else %>
      		<td> </td>
    	<% end %>

		<% if incident.incident_type_id != nil %>
			<% incident_type_name = IncidentType.find(incident.incident_type_id)%>
    		<td>
				<%= incident_type_name.name %>
			</td>
		<% else %>
			<td></td>
		<% end %>
    	<td><%= incident.location %></td>
    	<td><%= incident.latitude %></td>
    	<td><%= incident.longitude %></td>
		<% if @current_user %>
			<% if @current_user.role_id == 3 %>
				<% if incident.status%>
					<td>Yes</td>
				<% else %>
					<td>No</td>
				<% end %>
			<%end%>
		<%end%>
		
		<% if @current_user %>
			<%  if (added(incident) and @current_user.role_id != 3)  %>
				<td><%= button_to 'OPEN', incident_patients_path(incident), {:method => "get"}  %></td>
			<% elsif @current_user.role_id == 3 %>
				<td><%= button_to 'Delete', incident, :confirm => 'Are you sure?', :method => :delete  %></td>
			<% else%>
				<td><%= button_to 'JOIN', {:controller => 'incidents', :action => 'join_incident', :id => incident.id} %></td>
			<%end%>
		<%end%>
	</tr>
	<% end %>
</table>

<% if @current_user %>
	<% if @current_user.role_id != 3 %>
 		</div>
	<%end%>	
<%end%>

<div class="footerwrap">
	<br />
	<hr />
	<%= button_to 'START NEW MCI', new_incident_path, {:method => "get", :class => "LongButton"}%>
	<br />
</div>

app/views/incidents/report.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<div class="TopBar">
	<img class ="image"src ="../images/LogoWhite.png"/>
    <br />
	<h1 class="TopBarInterior">Incident Reports</h1>
	<br />
</div>
<br />

<%if !@incident.empty?%>
	<table id="mciTable">
  		<tr>
    		<th class="latitude">ID</th>
    		<th class="type">TYPE</th>
    		<th class="date">DATE</th>
    		<th class="location">LOCATION</th>
    		<th class="open"> </th>
    		<th class="open"> </th>
  		</tr>
  		<% @incident.each_with_index do |incident, y| %>
  			<% if y%2 == 0 %>
				<tr id ="even">
			<%else %>
          		<tr>
        	<% end%>
    		<td> <%=incident.id %></td>
    		<%incident_type_name = IncidentType.find(incident.incident_type_id) %>
    		<td> <%=incident_type_name.name %></td>
    		<td> <%=incident.date.strftime("%m/%d/%y %H:%M:%S %p %Z") %> </td>
    		<td> <%=incident.location %></td>
    		<td> <%= button_to "VIEW", {:controller => 'incidents', :action => 'viewreport', :id => incident.id}, {:onclick => "this.form.target = 'window'; window.open('','window', 'height = 650, width = 750, top = 20, left = 100, scrollbars = 0, toolbar = 0, status = 0, menubar = 0, location = 0')"}%> </td>
    		<td> <%= button_to "Download Report (PDF)", viewreport_path(incident.id, :format => "pdf") %> </td>
  		</tr>
		<% end %>
	</table>
<br />
<%else%>
	<h3> There are no closed incidents to generate reports.  <%= link_to 'Back', incidents_path %> </h3>
<% end %>

app/views/incidents/show.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->
<p id="notice"><%= notice %></p>


  <b>Date:</b>
  <%= @incident.date %>


<p>
  <b>Type:</b>
  <%= @incident.type %>


  <b>Location:</b>
  <%= @incident.location %>


  <b>Longitude:</b>
  <%= @incident.longitude %>


  <b>Latitude:</b>
  <%= @incident.latitude %>


  <b>Dispatchtime:</b>
  <%= @incident.dispatchTime %>


  <b>Arrivaltime:</b>
  <%= @incident.arrivalTime %>



  <b>Endtime:</b>
  <%= @incident.endTime %>

  <b>est patients:</b>
  <%= @incident.est_patient_count %>
</p>

<%form_for @incident, :url=> resourceupdate_path  do |f| %>
	ESTIMATED PATIENT COUNT <br />
 	<%= f.text_field :est_patient_count, :value => @incident.est_patient_count%>
	<br /><br />
	REQUESTED AMBULANCES <br />
	<%= f.text_field :requested_amb_count, :value => @incident.requested_amb_count%><br /><br />
	<%= f.submit "GO TO TRIAGE"%>
<% end %>

<%= link_to 'Back', edit_incident_path(@incident) %> |

app/views/incidents/viewreport.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<% if current_user  %>
	<% if @incident !=nil%>
		<div>
			<img class ="image"src ="../images/LogoWhite.png"/>
   			<div align="center">
    			<h3> Mass Triage Incident Report </h3><br/>
  			</div>
    		<div align="left">
    			<b>City of Santa Clara </b> <br/>
    			Paramedic Department<br/> <br/>
  			</div>
			<div align ="left">
    			Created on: <%=Time.now.strftime("%m/%d/%y %H:%M:%S %p %Z")%><br/>
    			Created by:<%= User.find(current_user.id).fname %> <%= User.find(current_user.id).lname %>
    		<br/>
  			</div>
		</div>
		<br/>
		<h3> Incident Details</h3>
		<table id="reportTable" >
  			<tr>  
				<th>Id</th> 
				<td> <%=@incident.id %></td>    
			</tr>
  			<tr>  
				<th>Date</th> 
				<td> <%=@incident.date.strftime("%m/%d/%y %H:%M:%S %p %Z") %> </td> 
			</tr>
   			<tr> 
				<th>Type</th> <%incident_type_name = IncidentType.find(@incident.incident_type_id) %>
         		<td><%= incident_type_name.name %></td>    
			</tr>
   			<tr> 
				<th>Location</th>  
				<td> <%=@incident.location %> </td> 
				</tr>
   			<tr> 
				<th>Duration</th>  
				<td>  <%= (Time.mktime(0)+ (@incident.updated_at - @incident.date) ).strftime("%H:%M:%S") %></td> 
			</tr>
   			<tr> 
				<th>Incident Commander</th>  
      			<% @leader =  role(@incident, 1) %>
     			<% if @leader != nil %>
     				<td> <%=@leader.fname  %>  <%=@leader.lname  %></td>
      			<%else%>  
					<td> </td>
      			<%end%>
			</tr>
   			<tr> 
				<th>Incident Dispatcher</th>
      			<% @leader =  role(@incident, 2) %>
      			<% if @leader != nil %>
          			<td> <%=@leader.fname  %>  <%=@leader.lname  %> </td>
      			<%else%>  
					<td> </td>
      			<%end%>
      		</tr>
    		<tr> 
				<th>Number of Responders</th>  
				<td><%=@incident.users.count%> </td> 
			</tr>
    		<tr> 
				<th>Number of patients</th>  
				<td> <%=@incident.patients.count%></td> 
			</tr>
    		<tr> 
				<th>Number of ambulances</th>  
				<td>  <%= (@incident.ambulances.count - 1)%> </td> 
			</tr>
		</table>
		<br/><br/>

		<h3>Incident Patient Summary by Triage Color</h3>

		<table class="summary">
      		<tr>
        		<td id="black_triage" class="black"><%= @incident.color_dist("Black", @incident.id) %></td>
        		<td id="red_triage" class="red"><%= @incident.color_dist("Red", @incident.id) %></td>
        		<td id="yellow_triage" class="yellow"><%= @incident.color_dist("Yellow", @incident.id) %></td>
        		<td id="green_triage" class="green"><%= @incident.color_dist("Green", @incident.id) %></td>
      		</tr>
    	</table>
		<br/><br/>
		<h3>Incident Patient Details</h3>
		<% @patient.each do |patient| %>
			<table id="reportTable" class="pbi_avoid">
  				<tr>
    				<th>Tag Number</th>
    				<th>Tag Color</th>
    				<th>Sex</th>
     				<th>Age</th>
    				<th>Complaint</th>
    				<th>Status</th>
    				<th> Ambulance</th>
    				<th> Hospital </th>
    				<th> Responder </th>
    				<th> Time added </th>
    				<% if patient.is_deleted != true %>
    					<th> Time Transported</th>
    					<th> Triage Time</th>
    				<%else%>
    					<th> Status</th>
    					<th> Time Deleted</th>
    				<%end%>
  				</tr>
  				<tr>
    				<td> <%=patient.numberOfTag%></td>
    				<td> <%=patient.tagColor%></td>
    				<td> <%=patient.sex %></td>
    				<td>  <%=patient.age %> <%= patient.ageType %></td>
    				<td> <%=patient.complaint %></td>
    				<td> <%=patient.status %> </td>
  					<%ambulance = Ambulance.find(patient.ambulance_id)%>
    				<%if ambulance != nil%>
    					<td> <%=ambulance.id %> </td>
    				<%else%>
    					<td> </td>
    				<%end%>
    				<%hospital = Hospital.find(patient.hospital_id)%>
    				<%if hospital != nil%>
    					<td> <%=hospital.name %> </td>
    				<%else%>
    					<td> </td>
    				<%end%>
    				<%  @user = user(patient.creating_user_id) %>

    				<td> <%=@user.fname %> <%=@user.lname %></td>
     				<td> <%=patient.created_at.strftime("%m/%d/%y %H:%M:%S %p %Z") %> </td>
     				<%  @transported = transport(@incident.id, patient.id) %>
     				<%if (@transported != nil and patient.is_deleted != true)  %>
        				<% if  @transported.value == "Transported"%>
          					<td> <%= @transported.updateTime.strftime("%m/%d/%y %H:%M:%S %p %Z")%> </td>
          					<td> <%= (Time.mktime(0)+ (@transported.updateTime - patient.created_at) ).strftime("%H:%M:%S") %> </td>
        				<%end %>
     				<%elsif patient.is_deleted == true %>
          				<td> DELETED </td>
          				<td> <%=patient.updated_at.strftime("%m/%d/%y %H:%M:%S %p %Z")%> </td>
     				<%else %>
          				<td> <%=patient.updated_at.strftime("%m/%d/%y %H:%M:%S %p %Z")%></td>
          				<td> <%= (Time.mktime(0)+ (patient.updated_at - patient.created_at) ).strftime("%H:%M:%S") %> </td>
     				<%end%>
  				</tr>
  				<% @update = updates(@incident.id, patient.id) %>
   				<%if !@update.empty?%>
      				<table id="reportTable">
        				<tr>
          					<th>Changed </th>
           					<th>Previous </th>
          					<th>Current </th>
          					<th> Update Time</th>
          					<th> Updated by</th>
        				</tr>
        				<% @update.each_with_index do |update, x| %>
       						<% if x%2 == 0 %>
          						<tr id ="even" class="pbi_avoid">
        					<%else %>
          						<tr>
        					<% end%>
          					<td> <%=update.updated%> </td>
          					<td> <%=update.previous%> </td>
          					<td> <%=update.value %></td>
          					<td> <%=update.updateTime.strftime("%m/%d/%y %H:%M:%S %p %Z") %></td>
          					<%  @user = user(update.user_id) %>
          					<td> <%=@user.fname %> <%=@user.lname %></td>
        				</tr>
        				<%end%>
      				</table>
   				<% end %> 
			</table>
			<br/> <br/> 
		<% end %>
		<br/> 
		<h3> Incident Responders</h3>
		<table id="reportTable">
  			<tr>
    			<th>First Name</th>
    			<th>Last Name</th>
    			<th>Role</th>
    			<th>Joined Incident </th>
  			</tr>
			<% @incident_user.each_with_index do |user, i| %>
        		<% if i%2 == 0 %>
          			<tr id ="even">
        		<%else %>
          			<tr>
        		<% end%>
    			<td> <%=user.fname %></td>
    			<td> <%=user.lname %></td>
       				<%if user.role_id == 1 %>
      					<td> Responder</td>
    				<%else%>
      					<td> Dispatcher</td>
      				<%end%>
      			<td> <%=user.created_at.strftime("%m/%d/%y %H:%M:%S %p %Z")%></td>
        	</tr>
			<% end %>
      </table>
	<br />
	<%else%>
	<h3> There are is no report available for Incident <%= params[:id]%>.  <%= link_to 'Back', report_path %> </h3>
	<% end %>
<%else%>
	<h3> You must be logged in to view report</h3>
<%end%>