config/routes.rb
MassTriage::Application.routes.draw do
 
  
  
  resources :incident_types

  match "login", :to => "user_sessions#new", :as => :login
  
  match "logout", :to => "user_sessions#destroy", :as => :logout

  match "patients/other", :to => "patients#other"
  
  match "administrators/index"  => "administrators#index", :as => "administrators"
  
  match "join_incident", :to => "incidents#join_incident", :as => :join_incident

  resources :user_sessions

  resources :users

  resources :hospitals

  

  resources :responders

  match "incidents/:id/closeincident" => "incidents#closeincident", :as => "closeincident"
  match "incidents/:incident_id/viewupdate" => "incidents#viewupdate", :as => "viewupdate"
  match "incidents/:incident_id/resourceupdate" => "incidents#resourceupdate", :as => "resourceupdate"
  match "incidents/:incident_id/patient_count" => "incidents#patient_count", :as => "patient_count"
  match "incidents/report" => "incidents#report", :as => "report"
  match "viewreport/:id" => "incidents#viewreport", :as => "viewreport"
  
  resources :incidents do
    resources :ambulances
    resources :patients
    member do
      get 'close'
    end
    
  end

 
  
  root :to => 'incidents#index'

end

app/models/patient.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class Patient < ActiveRecord::Base
  belongs_to :incident
  belongs_to :hospital
  belongs_to :ambulance
  has_many :updates
end

app/controllers/patients_controller.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

class PatientsController < ApplicationController
  layout 'patient'
  require 'json'
  before_filter :require_user
  
  def other
    @incident_id = params[:incident_id]
    puts "Incident ID = " + @incident_id
    date_millis = Time.at(params[:after].to_i/1000)
    puts "Time in client = " + date_millis.to_s
    @patients = Patient.where("incident_id = ? and updated_at > ?", @incident_id, Time.now-10.seconds)
    puts "# Updated Patients = " + @patients.count.to_s

    if (@patients.count > 0)
      @authenticity_token = params[:authenticity_token]
      puts "Authenticity token = " + @authenticity_token
      @new_patients = Patient.where("incident_id = ? and created_at > ?", @incident_id, Time.now-10.seconds)
      puts "New patients = " + @new_patients.count.to_s
      @triage = Patient.select("tagColor, count(*) as number").where("incident_id = ? and is_deleted = ?", @incident_id, false).group("tagColor")
      puts "Triage summary = " + @triage.count.to_s
      @general = Patient.where("incident_id = ? and is_deleted = ?", @incident_id, false)
      puts "#Total_Patients in incident = " + @general.count.to_s
      @hospitals = Hospital.order("name");
      puts "#Hospitals = " + @hospitals.count.to_s
      @all_ambulances = Ambulance.where("incident_id = ?", @incident_id).order("idAmbulance");
      puts "#Ambulances = " + @all_ambulances.count.to_s
    end

    @ambulances = Ambulance.where("incident_id = ? and updated_at > ?", @incident_id, Time.now-10.seconds).limit(1)
    puts "#Ambulances = " + @ambulances.count.to_s

    if (@ambulances.count > 0)
      @ambulances_assigned = Ambulance.select("status, count(*) as number").where("incident_id = ? and is_deleted = ?", @incident_id, false).group("status")
      puts "Ambulances Assigned = " + @ambulances_assigned.count.to_s
      @general_ambulances = Ambulance.where("incident_id = ? and is_deleted = ?", @incident_id, false).order("idAmbulance");
      puts "#Total Ambulances in incident = " + @general_ambulances.count.to_s
      @all_patients = Patient.where("incident_id = ? and is_deleted = ?", @incident_id, false)
      puts "#Patients = " + @all_patients.count.to_s
    end

    @incident = Incident.where("id = ? and updated_at > ?", @incident_id, Time.now-10.seconds)
    puts "#Incident = " + @incident.count.to_s

    if (@incident.count > 0)
      @incident_types = IncidentType.order("name");
      puts "#Incident types = " + @incident_types.count.to_s
    end

  end  

  def index    
    @incident = Incident.find(params[:incident_id])
    @patients = @incident.patients.all
    @patient = @incident.patients.new
    
    @hospitals = Hospital.find :all, :conditions => ['is_deleted is not ?', true]   
    @incidentType = IncidentType.find :all, :conditions => ['is_deleted is not ?', true]
    @stringIncidentType = json_incidentType(@incidentType)
   
    @ambulances = Ambulance.find :all, :conditions => ['is_deleted is not ? AND incident_id = ?', true, @incident.id]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @patients }
    end
  end


  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @patient }
    end
  end


  def new
    @incident = Incident.find(params[:incident_id])
    @patient = @incident.patients.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @patient }
    end
  end


  def edit
    @incident = Incident.find(params[:incident_id])
    @patient = @incident.patients.find(params[:id])
  end

  def create
    @incident = Incident.find(params[:incident_id])
    @patient = @incident.patients.create!(params[:patient])
    @patient.is_deleted = false;
    if(current_user.id != nil)
      @patient.creating_user_id = current_user.id
    end
    
    respond_to do |format|
      if @patient.save
        flash[:notice] = "You just added a patient!"
        format.html { redirect_to incident_patients_path }
        format.js
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def update
    @incident = Incident.find(params[:incident_id])
    @patient = @incident.patients.find(params[:id])
    @temp_patient=@patient.clone
    
    respond_to do |format|
      if(params[:patient])
        if @patient.update_attributes(params[:patient])
          @chng = PatientUpdate.new.patientchanges(params[:patient], @incident, @patient, current_user.id )
          flash[:notice] = "Patient successfully updated."
          if params[:patient][:numberOfTag]
            @chng.updated = "Tag Number"
            @chng.previous = @temp_patient.numberOfTag
            format.html {  render :text => params[:patient][:numberOfTag] }
            format.json  { head :ok }
          elsif params[:patient][:tagColor]
            @chng.updated = "Tag Color"
            @chng.previous =@temp_patient.tagColor
            format.html {  render :text => params[:patient][:tagColor] }
            format.json  { head :ok }
          elsif params[:patient][:sex]
            @chng.updated = "Sex"
            @chng.previous =@temp_patient.sex
            format.html {  render :text => params[:patient][:sex] }
            format.json  { head :ok }
          elsif params[:patient][:age]
            @chng.updated = "Age"
            @chng.previous =@temp_patient.age
            format.html {  render :text => params[:patient][:age] }
            format.json  { head :ok }
          elsif params[:patient][:ageType]
             @chng.updated = "Age Type"
             @chng.previous =@temp_patient.ageType
            format.html {  render :text => params[:patient][:ageType] }
            format.json  { head :ok }
          elsif params[:patient][:complaint]
             @chng.updated = "Complaint"
             @chng.previous =@temp_patient.complaint
            format.html {  render :text => params[:patient][:complaint] }
            format.json  { head :ok }
          else params[:patient][:status]
            @chng.updated = "Status"
            @chng.previous =@temp_patient.status
            format.html {  render :text => params[:patient][:status] }
            format.json  { head :ok }
          end
          @chng.save
        end
       
      elsif(params[:ambulance])
        if @patient.update_attributes(:ambulance_id => params[:ambulance][:idAmbulance])
          @chng = PatientUpdate.new.ambchanges(params[:ambulance][:idAmbulance], @incident, @patient, current_user.id )
          @chng.previous = Ambulance.find(@temp_patient.ambulance_id).idAmbulance
          @chng.save
          ambulanceName = Ambulance.find(params[:ambulance][:idAmbulance])
          format.html {  render :text => ambulanceName.idAmbulance }
          format.json  { head :ok }
        end
      else  
        if @patient.update_attributes(:hospital_id => params[:hospital][:name])
          @chng = PatientUpdate.new.hospitalchanges(params[:hospital][:name], @incident, @patient, current_user.id )
          @chng.previous = Hospital.find(@temp_patient.hospital_id).name
          @chng.save
          @ambulance = Ambulance.find(@patient.ambulance_id)
          if(@ambulance.idAmbulance != "Not yet defined")
            @ambulance.update_attributes(:hospital_id => params[:hospital][:name] )
          end
          @new_hospital = Hospital.find(params[:hospital][:name])
          format.html {  render :text => @new_hospital.name }
          format.json  { head :ok }
        end
      end
    end
  end


  def destroy
    @incident = Incident.find(params[:incident_id])
    @patient = @incident.patients.find(params[:id])
    if(@patient.update_attributes(:is_deleted => true ))
      respond_to do |format|
        format.html { redirect_to (incident_patients_url) }
        format.js
      end
    end
  end
  
  def json_incidentType(incidentType)
    hashIncidentType = Hash.new
    incidentType.each do |incidentType|
      hashIncidentType[incidentType.id] = incidentType.name
    end
    return JSON.generate(hashIncidentType)
  end
  
end

app/helpers/patients_helper.rb
# For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
# Developed by: Carnegie Mellon University - Team Triage
# Copyright:    Field Applications

module PatientsHelper
end

app/views/patients/_form.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<%= form_for [@incident, @patient] do |patient| %>
	<%= patient.label :numberOfTag, "TAG #" %>
	<%= patient.text_field :numberOfTag, :class => "MidField" %>
	<%= patient.select( :tagColor, [['Red','Red'],['Yellow','Yellow'],['Green','Green'],['Black','Black']],{}, {:class => "ShortField"}) %>
	<%= patient.select :sex, [['Female','Female'],['Male','Male']],{}, {:class => "ShortField"} %>
	<%= patient.label :age, "AGE" %>
	<%= patient.text_field :age, :class => "ShortField" %>
	<%= patient.select( :ageType, [['Years','Years'],['Months','Months'], ['Days', 'Days']],{}, {:class => "ShortField"}) %>
	<%= patient.label :complaint, "COMPLAINT"%>
	<%= patient.text_field :complaint, :class => "LongField"%>
	<%= patient.submit "ADD", :class => "ShortButton"%>
	<input type="button" id="extra_options_min" value="+" class ="RedShortButton" >
	<div id="extra_options">
        <%= patient.label "Status" %>
        <%= patient.select( :status, [['At Scene', 'At Scene'],['Transported','Transported'],['Missing/Left Scene','Missing/Left Scene']],{}, {:class => "ShortField"}) %>
        <%= patient.label "Hospital" %>
        <%= patient.collection_select(:hospital_id, @hospitals  ,:id, :name, {}, {:class => "LongField"}) %>
        <%= patient.label "Ambulance" %>
        <%= patient.collection_select(:ambulance_id, @ambulances, :id, :idAmbulance, {}, {:class => "LongField"}) %>
	</div>
<% end %>

app/views/patients/_patient.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<% if @incident.status == true %>
	<% if patient.is_deleted != true %>
    	<tr id="patient_<%= patient.id %>">
        	<td id="tagnum_<%= patient.id%>"><%= editable_field patient, :numberOfTag, {:update_url => incident_patient_path(@incident, patient)} %></td>
        	<% if patient.tagColor == "Black" %>
				<td id="color_<%= patient.id%>" class="blackPatient">
			<% elsif patient.tagColor == "Red" %>
				<td id="color_<%= patient.id%>" class="redPatient">
			<% elsif patient.tagColor == "Yellow" %>
				<td id="color_<%= patient.id%>" class="yellowPatient">
			<% else%>
				<td id="color_<%= patient.id%>" class="greenPatient">
			<% end %>					
			<%= editable_field patient, :tagColor, :type => 'select', :onblur => 'submit', :update_url => incident_patient_path(@incident, patient), :data => {'Green', 'Green', 'Black', 'Black', 'Yellow', 'Yellow', 'Red', 'Red'}%></td>
        	<% if patient.sex == "Female"%>
				<td id="sex_<%= patient.id%>" class="femalePatient">
			<% else %>
				<td id="sex_<%= patient.id%>" class="malePatient">
			<% end %>
			<%= editable_field patient, :sex, :type => 'select', :onblur => 'submit', :data => {'Female', 'Female', 'Male', 'Male'}, :update_url => incident_patient_path(@incident, patient) %></td>
        	<td id="age_<%= patient.id%>"><%= editable_field patient, :age, :update_url => incident_patient_path(@incident, patient) %></td>
        	<td id="ageType_<%= patient.id%>" class="ageType"><%= editable_field patient, :ageType, :type => 'select', :onblur => 'submit', :data => {'Years', 'Years', 'Months', 'Months', 'Days', 'Days'}, :update_url => incident_patient_path(@incident, patient) %></td>
        	<td id="complaint_<%= patient.id%>"><%= editable_field patient, :complaint, :update_url => incident_patient_path(@incident, patient) %></td>
        	<td id="patient_status_<%= patient.id%>" class="patient_status"><%= editable_field patient, :status, :type => 'select', :onblur => 'submit', :data => {'At Scene', 'At Scene', 'Transported', 'Transported', 'Missing/Left Scene', 'Missing/Left Scene'}, :update_url => incident_patient_path(@incident, patient) %></td>			
			<td id="hospital_patient_<%= patient.id %>" class="hospital_patient">
			<% hospital = Hospital.find(patient.hospital_id) %>
			<span class="editable" data-id="<%=patient.id%>" data-name="hospital[name]">
				<%= hospital.name %>
			</span>
			<script type="text/javascript">
				function listHospitals(){
					var hospitalList = '{';
					<% for a in @hospitals %>
						hospitalList = hospitalList + '"<%= a.id %>":"<%= escape_javascript(a.name) %>",';
					<% end %>
					hospitalList = hospitalList.substring(0, hospitalList.length-1);
					return hospitalList + '}';
				}
			    (function( $ ){
					$(function(){
			            var args = {data: function(value, settings) {
							// Unescape HTML
							var retval = value
			                .replace(/&amp;/gi, '&')
			                .replace(/&gt;/gi, '>')
			                .replace(/&lt;/gi, '<')
			                .replace(/&quot;/gi, "\"");
			              	return retval;
						}};
			            $.extend(args, {"name":"hospital[name]","data":listHospitals(),"onblur":"submit","method":"PUT","type":"select"});
			            $(".editable[data-id='<%=  patient.id %>'][data-name='hospital[name]']").editable("<%= incident_patient_path(@incident, patient.id) %>", args);
					});
				})( jQuery );
			</script>
			</td>
			<td id="ambulance_patient_<%= patient.id %>" class="ambulance_patient">
				<% ambulance = Ambulance.find(patient.ambulance_id) %>
				<span class="editable" data-id="<%=patient.id%>" data-name="ambulance[idAmbulance]">
					<%= ambulance.idAmbulance %>
				</span>
				<script type="text/javascript">
					function listAmbulances(){
						var ambulanceList = '{';
						<% for a in @ambulances %>
						ambulanceList = ambulanceList + '"<%= a.id %>":"<%= escape_javascript(a.idAmbulance) %>",';
						<% end %>
						ambulanceList = ambulanceList.substring(0, ambulanceList.length-1);
						return ambulanceList + '}';
					}
			        (function( $ ){
			          $(function(){
			            var args = {data: function(value, settings) {
			              // Unescape HTML
			              var retval = value
			                .replace(/&amp;/gi, '&')
			                .replace(/&gt;/gi, '>')
			                .replace(/&lt;/gi, '<')
			                .replace(/&quot;/gi, "\"");
			              return retval;
			            }};
			            $.extend(args, {"name":"ambulance[idAmbulance]","data":listAmbulances,"onblur":"submit","method":"PUT","type":"select"});
			            $(".editable[data-id='<%=  patient.id %>'][data-name='ambulance[idAmbulance]']").editable("<%= incident_patient_path(@incident, patient.id) %>", args);
			          });
			        })( jQuery );
				</script>
			 </td>
			 <td>
				<%= button_to "X", [@incident, patient], :method=>:delete, :class=>:destroy, :confirm=>"Are you sure?", :remote => true %>
			</td>
		</tr>
	<%end%>
<% else %>
    <% if patient.is_deleted != true %>
		<% if patient.is_deleted != true %>
			<tr id="patient_<%= patient.id %>">
        		<td id="tagnum_<%= patient.id%>"><%= patient.numberOfTag %></td>
        		<% if patient.tagColor == "Black" %>
					<td id="color_<%= patient.id%>" class="blackPatient">
				<% elsif patient.tagColor == "Red" %>
					<td id="color_<%= patient.id%>" class="redPatient">
				<% elsif patient.tagColor == "Yellow" %>
					<td id="color_<%= patient.id%>" class="yellowPatient">
				<% else%>
					<td id="color_<%= patient.id%>" class="greenPatient">
				<% end %>					
				<%= patient.tagColor%></td>
        		<% if patient.sex == "Female"%>
					<td id="sex_<%= patient.id%>" class="femalePatient">
				<% else %>
					<td id="sex_<%= patient.id%>" class="malePatient">
				<% end %>
				<%= patient.sex%></td>
        		<td id="age_<%= patient.id%>"><%= patient.age %></td>
        		<td id="ageType_<%= patient.id%>" class="ageType"><%= patient.ageType%></td>
        		<td id="complaint_<%= patient.id%>"><%= patient.complaint%></td>
        		<td id="patient_status_<%= patient.id%>" class="patient_status"><%= patient.status%></td>
				<td id="hospital_patient_<%= patient.id %>" class="hospital_patient">
					<% hospital = Hospital.find(patient.hospital_id) %>
					<span class="editable" data-id="<%=patient.id%>" data-name="hospital[name]"><%= hospital.name %></span>
			 	</td>
				<td id="ambulance_patient_<%= patient.id %>" class="ambulance_patient">
					<% ambulance = Ambulance.find(patient.ambulance_id) %>
					<span class="editable" data-id="<%=patient.id%>" data-name="ambulance[idAmbulance]"><%= ambulance.idAmbulance %></span>	
			 	</td>
    		</tr>
		<%end%>
	<%end%>
<%end%>

        

app/views/patients/create.js.erb
/*
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
*/

/* Insert a notice between the last comment and the comment form */
$("#patient-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Replace the count of comments */
$("#patient_count").html("<%= pluralize(Patient.count, 'Patient') %>");

/* Add the new comment to the bottom of the comments list */
$("#patients").append("<%= escape_javascript(render(@patient)) %>");

/* Highlight the new comment */
$("#patient_<%= @patient.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_patient")[0].reset();

app/views/patients/destroy.js.erb
/*
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
*/

/* Eliminate the patient by fading it out */
$('#patient_<%= @patient.id %>').fadeOut();
/* Replace the count of patient */
$("#patient_count").html("<%= pluralize(Patient.count, 'Patient') %>");

$('.delete_patient').bind('ajax:success', function() {  
    $(this).closest('tr').fadeOut();  
});

app/views/patients/edit.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h1>Editing patient</h1>

<%= render 'form' %>

 
<%= link_to 'Back', incident_patients_path %>

app/views/patients/index.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h2><span class ="SelectedTab">TRIAGE</span>   <span class ="UnselectedTab"><%= link_to "AMBULANCE", incident_ambulances_path(@incident) %></span>     <span class ="UnselectedTab"><%= link_to "CLOSE", close_incident_path(@incident) %></span></h2>
<hr />
<div id="incident_info" data-id="<%= @incident.id %>"></div>
<div id="form_token" data-id="<%= form_authenticity_token %>"></div>
<% if current_user %>
  <% if @incident.status == false %>
    <h1>THIS INCIDENT HAS BEEN CLOSED</h1>
  <% end %>
  <% if User.find(current_user.id).role_id == 1 and @incident.status== true%>
    <div class="incident" id="patient_input" data-id="<%= @incident.id %>">
      <br />
      <%= render 'form' %>
      <br />
    </div>
    <center><span class="highlight"<a class="min_toggle"id="min_patient_form" >PATIENT FORM</a></span></center>
  <% end %>
<% end %>
	<div id="patient-notice"></div>
	<br />


	<div class="scrollable2">
		<div class="patientsTable">
			<table id="tableForPatients">
				<tr>
		    		<th>TAG#</th>
		    		<th>COLOR</th>
		    		<th>SEX</th>
		    		<th>AGE</th>
		    		<th></th>
		    		<th>COMPLAINT(S)</th>
                                <th>STATUS</th>
				<th>HOSPITAL</th>
				<th>AMBULANCE</th>
				<% if @current_user %>
					<% if @current_user.role_id == 1 %>
						<th class="open">DELETE</th>
					<%end%>
				<%end%>
				</tr>		
				<tbody id="tbody_created_patients" class="tbody_created_patients">
                                <%= render :partial => @patients, :locals => {:list => true} %>
                                
				</tbody>
			</table>
		</div>
	
</div>
        
<br />

app/views/patients/new.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_patients_path %>

app/views/patients/show.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->

<p id="notice"><%= notice %></p>

<p>
  <b>Numberoftag:</b>
  <%= @patient.numberOfTag %>
</p>

<p>
  <b>Idincident:</b>
  <%= @patient.idIncident %>
</p>

<p>
  <b>Tagcolor:</b>
  <%= @patient.tagColor %>
</p>

<p>
  <b>Sex:</b>
  <%= @patient.sex %>
</p>

<p>
  <b>Age:</b>
  <%= @patient.age %>
</p>

<p>
  <b>Agetype:</b>
  <%= @patient.ageType %>
</p>

<p>
  <b>Complaint:</b>
  <%= @patient.complaint %>
</p>

<p>
  <b>Status:</b>
  <%= @patient.status %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/patients/update.js.erb
/*
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
*/

$('#patient_<%= @patient.id %>').removeClass('<%= @oldColor %>');
$('#patient_<%= @patient.id %>').addClass('<%= @newColor %>');