config/routes.rb
MassTriage::Application.routes.draw do
 
  
  
  resources :incident_types

  match "login", :to => "user_sessions#new", :as => :login
  
  match "logout", :to => "user_sessions#destroy", :as => :logout

  match "patients/other", :to => "patients#other"
  
  match "administrators/index"  => "administrators#index", :as => "administrators"
  
  match "join_incident", :to => "incidents#join_incident", :as => :join_incident

  resources :user_sessions

  resources :users

  resources :hospitals

  

  resources :responders

  match "incidents/:id/closeincident" => "incidents#closeincident", :as => "closeincident"
  match "incidents/:incident_id/viewupdate" => "incidents#viewupdate", :as => "viewupdate"
  match "incidents/:incident_id/resourceupdate" => "incidents#resourceupdate", :as => "resourceupdate"
  match "incidents/:incident_id/patient_count" => "incidents#patient_count", :as => "patient_count"
  match "incidents/report" => "incidents#report", :as => "report"
  match "viewreport/:id" => "incidents#viewreport", :as => "viewreport"
  
  resources :incidents do
    resources :ambulances
    resources :patients
    member do
      get 'close'
    end
    
  end

 
  
  root :to => 'incidents#index'

end

app/views/layouts/application.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->
<!DOCTYPE html>
<html>
	<head>
  		<title>MTAP</title>
  		<%= stylesheet_link_tag :all , :media => "screen" %>
  		<%= javascript_include_tag :defaults %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  		<%= javascript_include_tag "jquery-rails.js" %>
  		<%= javascript_include_tag "jquery.jeditable.js" %>
  		<%= javascript_include_tag "jquery.cookie.js" %>
  		<%= javascript_include_tag "jquery.tablesorter.js" %>
  		<%= javascript_include_tag "autocomplete-rails.js" %>
  		<%= csrf_meta_tag %>
	</head>
	
	<body> 
	<% if @current_user %>
		<% if @current_user.role_id == 3 %>	
			<table id="mciTable">
				<th class="open"><%= link_to 'Type of incidents', incident_types_path %></th>
				<th class="open"><%= link_to 'Hospitals', hospitals_path %></th>
				<th class="open"><%= link_to 'Users', users_path %></th>
				<th class="open"><%= link_to 'Incidents',  incidents_path %></th>
				<th class="open"><%= link_to 'Reports',  report_path %></th>		
				<th class="open">LOGGED IN USER: <%= @current_user.username%></th>
				<th class="open"><%= link_to "Logout", :logout %></th>
			</table>
		<% end %>
	<% end %>
	<%= yield %>	
	</body>
</html>

app/views/layouts/patient.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->
<!DOCTYPE html>
<html>
	<head>
  		<title>MTAP</title>
  		<%= stylesheet_link_tag :all %>
  		<%= javascript_include_tag :defaults %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  		<%= javascript_include_tag "jquery-rails.js" %>
  		<%= javascript_include_tag "jquery.jeditable.js" %>
  		<%= javascript_include_tag "jquery.cookie.js" %>
  		<%= javascript_include_tag "jquery.tablesorter.js" %>
  		<%= javascript_include_tag "autocomplete-rails.js" %>
  		<%= csrf_meta_tag %>
	</head>
	<body>
  		<div class="TopBar">
  			<div id="collapsable" class="header_bar">
  				<div class="left-long">
    				<% incidentTypeName = IncidentType.find(@incident.incident_type_id)%>
						<a href="#" id="tt"><b>INCIDENT</b></a>
						<span class="details" id="tooltip">
							<%= editable_field @incident, :description, :update_url => resourceupdate_path %>
						</span>
						<br />
        				<%= @incident.date %><br />
						<%= div_for incidentTypeName do %>
          					<div id="incident_type_" class="incident_type_">
								<%= editable_field incidentTypeName, :name, :type => 'select', :onblur => 'submit', :data => @stringIncidentType, :update_url => resourceupdate_path %>
							</div>
						<% end %>
						<div id="incident_location_" class="incident_location_">
							<%= editable_field @incident, :location, :update_url => resourceupdate_path%>
						</div>
        				LAT: 
						<span id="incident_latitude_" class="incident_latitude_">
							<%= editable_field @incident, :latitude, :update_url => resourceupdate_path %>
						</span> | LONG: 
						<span id="incident_longitude_" class="incident_longitude_">
							<%= editable_field @incident, :longitude, :update_url => resourceupdate_path %>
						</span>
  					</div>	
  					<div class="left">
    					<b>PATIENTS</b><br/>
    					ESTIMATED: <%= @incident.est_patient_count %><br />
    					<div id="tagged">
							TAGGED: <%= @incident.count_patient(@incident.id).count.to_s%><br />
						</div>
    					<table class="summary">
      						<tr>
        						<td id="black_triage" class="black"><%= @incident.color_dist("Black", @incident.id) %></td>
        						<td id="red_triage" class="red"><%= @incident.color_dist("Red", @incident.id) %></td>
        						<td id="yellow_triage" class="yellow"><%= @incident.color_dist("Yellow", @incident.id) %></td>
        						<td id="green_triage" class="green"><%= @incident.color_dist("Green", @incident.id) %></td>
      						</tr>
    					</table> 
   					</div>
  					<div class="left-long">
    					<b>AMBULANCES</b><br/>
    					<table class="ambulance">
      						<tr>
        						<td id="requested_amb">REQUESTED: <%= @incident.requested_amb_count %></td>
        						<td id="en_route_amb">EN ROUTE: <%= @incident.amb_count("En Route", @incident.id)%><br /></td>
      						</tr>
      						<tr>
        						<td id="arrived_amb">AT SCENE: <%= @incident.amb_count("At Scene", @incident.id) %></td>
        						<td id="delayed_amb">DELAYED: <%= @incident.amb_count("Delayed", @incident.id) %><br /></td>
      						</tr>
      						<tr>
        						<td id="staged_amb">STAGING: <%= @incident.amb_count("Staging", @incident.id) %></td>
        						<td id="transported_amb">TRANSPORTED: <%= @incident.amb_count("Transported", @incident.id) %></td>
      						</tr>
    					</table>
  					</div>
  					<div class="right">
    					<% if current_user %>
      						LOGGED IN: <%= link_to "LOGOUT", :logout %><br/>
      						<%= current_user.username%><br />
      						<% if User.find(current_user.id).role_id == 1 %>
        						RESPONDER
      						<% elsif User.find(current_user.id).role_id == 2 %>
        						DISPATCHER
      						<% end %>
      							<br />
      						<%= link_to "EXIT INCIDENT", incidents_path %>
    					<% else %>
      						NO USER
      						<br /><%= link_to "LOGIN", :login %>
    					<% end %>    
    					<br />
  					</div>
   				</div>
  				<hr />
				<span class="highlight" id="min" >SUMMARY RIBBON</span>
			</div>
			<%= yield %>
		</body>
</html>

app/views/layouts/report.html.erb
<!--
For more information on the technology stack selected, please refer to the document "Technology feasibility analysis"
Developed by: Carnegie Mellon University - Team Triage
Copyright:    Field Applications 
-->
<!DOCTYPE html>
<html>
	<head>
  		<title>MTAP - Reports</title>
  		<%= stylesheet_link_tag "printMedia" , :media => "all" %>
  		<%= javascript_include_tag :defaults %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  		<%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  		<%= javascript_include_tag "jquery-rails.js" %>
  		<%= javascript_include_tag "jquery.jeditable.js" %>
  		<%= javascript_include_tag "jquery.cookie.js" %>
  		<%= javascript_include_tag "jquery.tablesorter.js" %>
  		<%= javascript_include_tag "autocomplete-rails.js" %>
  	<%= csrf_meta_tag %>
	</head>
	<body> 
		<%= yield %>
	</body>
</html>